---
language: ruby
bundler_args: --without development
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
rvm:
  - 2.1.9
  - 2.3.1
env:
  matrix:
    - MCOLLECTIVE_GEM_VERSION="~> 2.7.0"
    - MCOLLECTIVE_GEM_VERSION="~> 2.8.0"
    - MCOLLECTIVE_GEM_VERSION="~> 2.9.0"
notifications:
  email: false
